language: bash
# command to install dependencies
sudo: true
install:
    - sudo apt-get install bedtools
    - sudo pip install -r tests/requirements.txt
# command to run tests
script:
    - bash tests/testCytomod.sh
