language: bash
# command to install dependencies

dist: bionic

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - hdf5-tools
      - bc
      - bedtools

install:
    - pip install --user --upgrade pip
    - cat tests/requirements.txt | xargs -n 1 pip install --user --upgrade
cache:
    apt: true
    directories:
        - $HOME/.cache/pip
        - $HOME/.local/bin
before_script:
    - python -V
    - pip freeze
# command to run tests
script:
    - cd tests
    - ./testCytomod.sh
    - ./testConvertToOrModifyExtreMEME.sh
    - ./testGenModPermutationsFromUnmodMotifs.sh
