language: bash
# command to install dependencies
sudo: true
cache:
    - apt
    - pip
install:
    - sudo apt-get install zlib1g-dev zlib bedtools libhdf5-serial-dev hdf5-tools bc
    - cat tests/requirements.txt | sudo -H xargs -n 1 pip install
# command to run tests
script:
    - cd tests && ./testCytomod.sh
