language: bash
# command to install dependencies
sudo: true
install:
    - sudo apt-get install bedtools
    - pip install -r requirements.txt
# command to run tests
script:
    - bash tests/testCytomod.sh
